# Generated by Django 4.0.2 on 2022-06-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiTodo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='updatedDate',
            new_name='updateDate',
        ),
        migrations.AddField(
            model_name='todo',
            name='done',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
